### PR TITLE
Allow more generic use of Maven Plugin for non Spring Cloud projects

### PR DESCRIPTION
**Pull request by bartveenstra**
The maven plugin is a wonderfull peace of kit I use to create Spring Cloud Streams and Tasks without binding myself to either kafka or rabbit mq. 

However, when testing this plugin in my closed environment for sources that are project specific, the generated projects consisted of many hard coded defaults that are not applicable to my project. 

I have make the Distribution Management and docker hub organisation configurable through properties and configuration to adopt use of this excellent maven plugin in  projects

### CODE REVIEW

**Comment by sabbyanandan** [comment]
Hi, @bartveenstra. This looks great! We will review and get back to you if we have any comments.  

That said, I'd love to learn more about how you're using the App Starters. We are putting some thoughts together to redesign the current infrastructure, so it is more natural to extend and contribute back to the community. So any feedback if you have in regards to the App Starters design/purpose, we are all ears.

**Comment by bartveenstra** [comment]
> Hi, @bartveenstra. This looks great! We will review and get back to you if we have any comments.
> 
> That said, I'd love to learn more about how you're using the App Starters. We are putting some thoughts together to redesign the current infrastructure, so it is more natural to extend and contribute back to the community. So any feedback if you have in regards to the App Starters design/purpose, we are all ears.

Hi @sabbyanandan,

I am currently working on a prototype to help our customers ingest large amounts of data into our software and SCDF does tick a lot of boxes. I started with some of the normal starters, but I quickly ran into issues that i do not know what kind of deployment platforms our customers are going to use, so I started looking into abstractions and how the already published starters use the bindings available. 

I am planning to use SCDF in a more ETL process in which I use stream/task components either OOTB of custom. 

SCDF on K8s provides  a lot of what I need to achieve and due to the polyglot nature I am also working on some GraalVM components  to reduce the footprint of those  components on K8s (65MB for transforming json to another json format is a bit too much for my taste) 

I am very interested in how this plugin will develop over time and how starters are structured in the future. Do you have any documentation available on the future plans on how the infrastructure is going to look like?

Kind regards,

Bart Veenstra

**Comment by sobychacko** [comment]
@bartveenstra Thank you for the PR and the updates on your use cases. We are going to make some major changes in the way Spring Cloud Stream apps are structured to make them more extensible on other platforms (for ex. [project riff](https://projectriff.io/)). They will continue to work in the same way as it is today on SCDF, but the underlying code base might change. We envision that there are going to be some changes at the maven plugin level to accommodate these fundamental changes, but not a lot though. We will take a look at your PR and decide how best it can fit in the current plugin code. Once again, thanks for the PR.

**Comment by sobychacko** [comment]
@bartveenstra I know we are very late in responding here. Were you following the latest on the apps side? [Here](https://github.com/spring-cloud/stream-applications) is the new repo where we are migrating all our existing app starters as functions. The plugin also is redesigned considerably since the time you issued the PR. If you get a chance, could you take a look and see if the PR is still relevant for your needs? I think we probably need to re-work on this PR. Apologies for the delay here. Thank you!

**Comment by sobychacko** [comment]
@bartveenstra Closing this PR. See my comment above for the new plans for the plugin. Thank you!

**Pull request closed without merging**
