### PR TITLE
This PR adds  spring-cloud-app-starter-metadata-gradle-plugin

### PR DESCRIPTION
**Pull request by jvmlet**
Gradle plugin to aggregate the spring metadata

Resolves spring-cloud/spring-cloud-app-starters-maven-plugins#19

### CODE REVIEW

**Comment by sobychacko** [comment]
Hi, @jvmlet Thank you for this PR. It looks like you are building a Spring Cloud Stream app and are using gradle as the build system. I suppose that's where the requirement for the gradle plugin came up. Did you not use the app generator or docs plugin in the project since you directly created the app? We need to decide if this is the right home for the plugin as this only contains maven plugins (so far). Could you add an integration test that somehow verifies that the metadata is generated from a real spring boot app using this plugin?

**Comment by jvmlet** [comment]
@sobychacko , I was explicitely advised by @sabbyanandan to add the gradle plugin to this repo (see comments in  https://github.com/spring-cloud/spring-cloud-app-starters-maven-plugins/issues/19 )
The  integration test is also there (see `test` directory)

**Comment by jvmlet** [comment]
`src/test/resources/testProject` simulates the real spring boot app.

**Comment by sobychacko** [comment]
@jvmlet Sorry for the delay in merging this PR. I am about to merge this, but all the classes are missing copyright notice, author tag etc. Could you add those? Also, there are a few unused imports and imports with `*`. Please clean them up as well. Then its ready for merging upstream. Thanks.

**Comment by jvmlet** [comment]
Sure, I'll be able to accomplish this nearest Monday

**Comment by jvmlet** [comment]
@sobychacko , I've added the copyrigths and cleaned the imports.

**Comment by sobychacko** [comment]
LGTM - polished, squashed the commit and merged upstream.
Thank you for the PR @jvmlet. Next step is to create a CI plan and a snapshot build for the plugin. If you see a pressing need for that, please raise an issue.

**Pull request closed without merging**
